import { SoundProfile, SwitchProfileId } from '../types';

export const SWITCH_PROFILES: Record<SwitchProfileId, SoundProfile> = {
  creamy: {
    id: 'creamy',
    name: 'Creamy Linear',
    categoryName: 'Smooth & Buttery',
    tagline: 'Deep, muffled, ultra-smooth POM glide with factory lube acoustic profile',
    description: 'Models the coveted buttery smooth sound of hand-lubed linear switches (Gateron Milky Yellow / NovelKeys Cream). Characterized by a damped high-end, velvety low-mid resonance, and zero scratchiness.',
    acousticSignature: 'Low-pass filtered ~1100Hz, gentle soft-cushion attack, buttery foam dampening',
    accentColor: '#d2b48c', // Tan / Warm Khaki
    badgeBg: 'bg-amber-800/30 text-amber-200 border-amber-600/40',
    gradientBorder: 'from-amber-200 via-yellow-600 to-amber-800',
    ghostNumber: '01',
    keycapTheme: {
      bg: 'bg-stone-900/70',
      text: 'text-amber-100',
      border: 'border-amber-700/50',
      activeBg: 'bg-amber-300',
      activeText: 'text-stone-950',
      glow: 'rgba(210, 180, 140, 0.55)',
    },
    basePitch: 280,
    pitchJitter: 0.04,
    damping: 0.85,
    plateResonance: 0.35,
    bottomOutDepth: 0.75,
    clickSharpness: 0.0,
    popSweep: 0.0,
    lubeLevel: 0.95,
    releaseVolume: 0.35,
    spacebarThockFactor: 1.4,
  },
  poppy: {
    id: 'poppy',
    name: 'Marbly Poppy',
    categoryName: 'Bubbly & Marbly',
    tagline: 'Distinct bubble-wrap pop with PE foam acoustic resonance and high rebound',
    description: 'The viral ASMR sensation: sounds like rolling smooth glass marbles on polished wood. Utilizes PE foam sheet modulation to turn each keypress into a bubbly, bright, addictive pop (OwLab Jelly Epoch / Akko CS Jelly).',
    acousticSignature: 'Dynamic 1900Hz to 600Hz downward frequency sweep, marbly PE foam squish',
    accentColor: '#ec4899', // Pink / Marble pop
    badgeBg: 'bg-pink-500/20 text-pink-300 border-pink-500/40',
    gradientBorder: 'from-pink-400 via-pink-500 to-rose-600',
    ghostNumber: '02',
    keycapTheme: {
      bg: 'bg-pink-950/40',
      text: 'text-pink-100',
      border: 'border-pink-700/40',
      activeBg: 'bg-pink-500',
      activeText: 'text-pink-950',
      glow: 'rgba(236, 72, 153, 0.45)',
    },
    basePitch: 360,
    pitchJitter: 0.045,
    damping: 0.4,
    plateResonance: 0.6,
    bottomOutDepth: 0.6,
    clickSharpness: 0.15,
    popSweep: 0.95,
    lubeLevel: 0.6,
    releaseVolume: 0.5,
    spacebarThockFactor: 1.35,
  },
  clacky: {
    id: 'clacky',
    name: 'Crisp Clack',
    categoryName: 'Bright & Snappy',
    tagline: 'High-frequency punchy snap on rigid aluminum plate with ABS keycaps',
    description: 'Energetic, articulate, and satisfyingly bright. Emulates the snappy top-mount aluminum plate sound of Cherry MX Brown / HyperX Reds with dense ABS keycaps, providing crisp acoustic precision for fast typists.',
    acousticSignature: 'High-register 3200Hz transient, metallic aluminum ping, snappy return top-out',
    accentColor: '#6b7280', // Industrial Gray
    badgeBg: 'bg-gray-500/20 text-gray-300 border-gray-500/40',
    gradientBorder: 'from-gray-400 via-gray-500 to-zinc-700',
    ghostNumber: '03',
    keycapTheme: {
      bg: 'bg-zinc-900/70',
      text: 'text-gray-100',
      border: 'border-zinc-700/60',
      activeBg: 'bg-gray-400',
      activeText: 'text-zinc-950',
      glow: 'rgba(107, 114, 128, 0.5)',
    },
    basePitch: 480,
    pitchJitter: 0.05,
    damping: 0.2,
    plateResonance: 0.75,
    bottomOutDepth: 0.4,
    clickSharpness: 0.35,
    popSweep: 0.0,
    lubeLevel: 0.25,
    releaseVolume: 0.65,
    spacebarThockFactor: 1.15,
  },
  thocky: {
    id: 'thocky',
    name: 'Deep Thock',
    categoryName: 'Hollow & Bassy',
    tagline: 'Resonant, deep bass acoustic thud with heavy brass/polycarbonate housing',
    description: 'The holy grail mechanical keyboard acoustic: deep, hollow bass thump with rich bottom-out body (Boba U4T, Holy Panda, or Gateron Oil Kings in a gasket-mounted aluminum case with brass weight).',
    acousticSignature: 'Resonant 180Hz fundamental, hollow cavity reflection, maximum bottom-out sub-bass weight',
    accentColor: '#6366f1', // Electric Indigo
    badgeBg: 'bg-indigo-500/20 text-indigo-300 border-indigo-500/40',
    gradientBorder: 'from-indigo-500 via-indigo-600 to-violet-700',
    ghostNumber: '04',
    keycapTheme: {
      bg: 'bg-indigo-950/40',
      text: 'text-indigo-100',
      border: 'border-indigo-700/40',
      activeBg: 'bg-indigo-500',
      activeText: 'text-indigo-950',
      glow: 'rgba(99, 102, 241, 0.55)',
    },
    basePitch: 195,
    pitchJitter: 0.035,
    damping: 0.65,
    plateResonance: 0.85,
    bottomOutDepth: 0.95,
    clickSharpness: 0.05,
    popSweep: 0.0,
    lubeLevel: 0.75,
    releaseVolume: 0.4,
    spacebarThockFactor: 1.85,
  },
  buckling: {
    id: 'buckling',
    name: 'Buckling Spring',
    categoryName: 'Iconic Vintage',
    tagline: 'Crisp high-pitched mechanical snap & resonant metallic spring coil ping',
    description: 'The unmistakable sound of the legendary 1980s IBM Model M. Pure crisp mechanical snap combined with the resonant harmonic unbuckle ping of the vibrating coil spring.',
    acousticSignature: '3.6kHz crisp mechanical snap, 2.78kHz harmonic spring coil unbuckle ping',
    accentColor: '#84cc16', // Lime
    badgeBg: 'bg-lime-500/20 text-lime-300 border-lime-500/40',
    gradientBorder: 'from-lime-400 via-lime-500 to-emerald-600',
    ghostNumber: '05',
    keycapTheme: {
      bg: 'bg-lime-950/40',
      text: 'text-lime-100',
      border: 'border-lime-700/40',
      activeBg: 'bg-lime-400',
      activeText: 'text-lime-950',
      glow: 'rgba(132, 204, 22, 0.55)',
    },
    basePitch: 100,
    pitchJitter: 0.06,
    damping: 0.12,
    plateResonance: 0.98,
    bottomOutDepth: 0.92,
    clickSharpness: 0.98,
    popSweep: 0.0,
    lubeLevel: 0.0,
    releaseVolume: 0.95,
    spacebarThockFactor: 1.75,
  },
  'hi-fi': {
    id: 'hi-fi',
    name: 'Glass & Ceramic Pop',
    categoryName: 'High-Pitch Crystal',
    tagline: 'Glazed ceramic keycaps on brass plate with crystal-clear high-definition resonance',
    description: 'An acoustic marvel inspired by custom Cerakey ceramic keycaps on an integrated brass plate. Produces an ultra-crisp, resonant crystalline ring and bright, glass-like clink with every keystroke.',
    acousticSignature: 'Dual resonance 1850Hz & 3900Hz crystal bell overtone, glass-on-porcelain chime',
    accentColor: '#38bdf8', // Crystal Sky Blue
    badgeBg: 'bg-sky-500/20 text-sky-300 border-sky-500/40',
    gradientBorder: 'from-sky-400 via-cyan-400 to-blue-600',
    ghostNumber: '06',
    keycapTheme: {
      bg: 'bg-sky-950/40',
      text: 'text-sky-100',
      border: 'border-sky-700/40',
      activeBg: 'bg-sky-400',
      activeText: 'text-sky-950',
      glow: 'rgba(56, 189, 248, 0.5)',
    },
    basePitch: 640,
    pitchJitter: 0.04,
    damping: 0.18,
    plateResonance: 0.9,
    bottomOutDepth: 0.35,
    clickSharpness: 0.7,
    popSweep: 0.6,
    lubeLevel: 0.4,
    releaseVolume: 0.7,
    spacebarThockFactor: 1.25,
  },
};

export const DEFAULT_AUDIO_SETTINGS = {
  masterVolume: 0.85,
  pitchMultiplier: 1.0,
  pitchJitterEnabled: true,
  stereoPanEnabled: true,
  releaseSoundEnabled: true,
  lubeModifier: 0.5,
  spacebarBoost: 1.4,
  reverbAmount: 0.25,
  isMuted: false,
};

export const DEFAULT_OVERLAY_SETTINGS = {
  enabled: true,
  position: 'bottom-dock' as const,
  opacity: 0.92,
  showActiveKey: true,
  showOscilloscope: true,
  showWpm: true,
  showSoundProfile: true,
  visualFeedbackMode: 'ripple' as const,
  size: 'normal' as const,
};

export const DEFAULT_AMBIENT_SETTINGS = {
  enabled: false,
  rainVolume: 0.0,
  cafeVolume: 0.0,
  tapeHissVolume: 0.0,
  roomResonanceVolume: 0.0,
};
